version: "3"

services: 
    data_manager:
        container_name: data_manager
        build: ./src/dataManager/
        ports:
            - 5000

    database:
        container_name: database
        image: mongo:4.2.2
        ports:
            - 27017
        volumes:
            - mongodb:/data/db
    
    tmp_database:
        container_name: tmp_database
        image: mongo:4.2.2
        ports:
            - 27017
        volumes:
            - tmpmongodb:/data/db

    data_analysis:
        container_name: data_analysis
        build: ./src/dataAnalysis
        ports:
            - 5000
    
    data_collector:
        container_name: data_collector
        build: ./src/dataPreprocessing/dataCollector
        env_file:
            - "auth.env"


    data_cleaner:
        container_name: data_cleaner
        build: ./src/dataPreprocessing/dataCleaner
    
    grafana_connector:
        container_name: grafana_connector
        build: ./src/grafana/grafanaConnector
        ports:
            - 5000

    grafana:
        container_name: grafana
        build: ./src/grafana/grafana
        ports: 
            - 3000
    
    nginx:
    restart: always
    build: ./src/nginx
    container_name: nginx
    links:
        - "device_manager"
        - "grafana"
    ports:
        - "80:80"


volumes:
    mongodb:
    tmpmongodb:
