version: "3"

services: 
    data_manager:
        container_name: data_manager
        build: ./src/dataManager/
        ports:
            - 5000

    database:
        container_name: database
        image: mongo:4.2.2
        ports:
            - "27017:27017"
        volumes:
            - mongodb:/data/db
    
    tmp_database:
        container_name: tmp_database
        image: mongo:4.2.2
        ports:
            - 27017
        volumes:
            - tmpmongodb:/data/db

    #TODO: set up grafana
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"

    data_analysis:
        container_name: data_analysis
        build: ./src/dataAnalysis
        ports:
            - "5001:5001"
    
    data_collector:
        container_name: data_collector
        build: ./src/dataCollector
        ports:
            - "5002:5002"

    data_cleaner:
        container_name: data_cleaner
        build: ./src/dataCleaner
    
    grafana_request:
        container_name: grafana_request
        build: ./src/grafanaRequest
        ports:
            - 5003


volumes:
    mongodb:
    tmpmongodb:
