version: "3"

services: 
    data_manager:
        container_name: data_manager
        build: ./src/dataManager/
        ports:
            - 5000

    database:
        container_name: database
        image: mongo:4.2.2
        #environment:
        #    MONGO_INITDB_ROOT_USERNAME: root
        #    MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017
        volumes:
            - mongodb:/data/wifiSniffer/db
    
    tmp_database:
        container_name: tmp_database
        image: mongo:4.2.2
        #environment:
        #    MONGO_INITDB_ROOT_USERNAME: root
        #    MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - 27017
        volumes:
            - tmpmongodb:/data/wifiSniffer/tmpdb

    dashboard:
        container_name: dashboard
        build: ./src/dashboard/
        ports:
            - "80:80"

    data_analysis:
        container_name: data_analysis
        build: ./src/dataAnalysis
        ports:
            - "5001:5001"
    
    data_collector:
        container_name: data_collector
        build: ./src/dataCollector
        ports:
            - "5002:5002"

    data_cleaner:
        container_name: data_cleaner
        build: ./src/dataCleaner


volumes:
    mongodb:
    tmpmongodb:
